### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by shyiko** [jeremymailen/kotlinter-gradle#1]
Hey Jeremy,

I've been watching this project for couple of days and I think it's awesome. Just wanted to say Thank You for doing this and let you know that I have added a link to this repo in https://github.com/shyiko/ktlint#-with-gradle. 

Keep it up!

Enjoy your weekend,
Stan.

**Comment by jeremymailen** [comment]
Thanks Stan! I really appreciate it. You've done the challenging part by making the linter itself so thank you for helping the Kotlin community. Many dev teams want a linter when they adopt a new language and auto-formatting is an extra bonus.

First time I've written a full Gradle plugin. I hope it helps teams plug it in to their build smoothly. Thoughts, feature requests, and contributions welcome!

**Comment by samarjan92** [comment]
Can I create a custom rules with that wrapper?

**Comment by jeremymailen** [comment]
Yes, you can apply your own customer rulesets. They just need to be in the gradle buildscript classpath:
```groovy
buildscript {
    dependencies {
        classpath files('libs/my-custom-ktlint-rules.jar')
    }
}

plugins {
    ...
    id 'org.jmailen.kotlinter' version '0.9.3'
}
...
```
Of course if your rules are in an artifact repository you can use a maven coordinate there as well.

This will work since this plugin uses the ktlint engine directly rather than wrapping around execution of the tool.

I'll document this in the readme. Thanks!
