### ISSUE TITLE
disabledRules broken in 2.3.0?

### ISSUE THREAD

**Issue by henrik242** [jeremymailen/kotlinter-gradle#130]
After upgrading from 2.2.0 to 2.3.0 `formatKotlin` complains about wildcards: `Format could not fix > [no-wildcard-imports] Wildcard import`, and it tries to order my imports.  This is explicitly disabled in my kotlin dsl config:
```
apply(plugin: "org.jmailen.kotlinter")
kotlinter {
    disabledRules = ["no-wildcard-imports", "import-ordering"]
}
```
Any ideas which change could have triggered this?

**Comment by jeremymailen** [comment]
This is working for me in both single and multi-module projects.

Do you have a `.editorconfig` and also can you share more detail on your configuration?

**Comment by henrik242** [comment]
This is the context:
```
compileKotlin.kotlinOptions.jvmTarget = 1.8
compileGroovy.classpath += files(compileKotlin.destinationDir)
compileTestGroovy.classpath += files(compileTestKotlin.destinationDir)
sourceSets.main.kotlin.srcDirs = ["src/main/java"]
sourceSets.test.kotlin.srcDirs = ["src/test/java"]

apply(plugin: "org.jmailen.kotlinter") // Must be after kotlin"s sourceSets definitions

kotlinter {
    disabledRules = ["no-wildcard-imports", "import-ordering"]
}

assemble.dependsOn(formatKotlin)
```
Don't know if that helps? I don't have an `.editorconfig`

**Comment by henrik242** [comment]
It's definitely the changes by @mateuszkwiecinski that broke something. Haven't been able to figure out how, though.

**Comment by mateuszkwiecinski** [comment]
Huh, that's strange 🤔 
I copy pasted the code you shared and it seems to be working as expected. Similar case is already covered by tests.
Would you be able to share a simple repository that reproduces the issue? 
And in the meantime could you add:
```
tasks.named("lintKotlinMain") { // task name that fails
    println("srouceSets")
    sourceSets.all {
        println("${it.name} -> ${it.java.srcDirs}")
        println("${it.name} -> ${it.kotlin.srcDirs}")
    }
    println("rules")
    println(kotlinter.disabledRules.join(","))
    println("ktlint")
    println(ktLintParams)
}
```
and share the console output? That could give me some insights why `disabledRules` aren't passed.
And just FYI: the `// Must be after kotlin"s sourceSets definitions` shoudln't be needed. You should be able to apply kotlinter at the top. 

The conclusion I draw is it would be nice to have additional logging and to simply ask for adding an e.g. `--info` argument.

**Comment by henrik242** [comment]
This is a huge multiproject build, so it's not all that trivial to create a simple repository.  I'll try, though :)

In the meantime, here's the output:
```
Evaluating project ':flight-common' using build file '/Users/henarons/src/travel-app/flight/common/flight-common.gradle.kts'.
--sourceSets--
main -> []
main -> KotlinSourceSet container
moduleTest -> []
moduleTest -> KotlinSourceSet container
test -> []
test -> KotlinSourceSet container
--rules--
no-wildcard-imports,import-ordering
--ktlint--
KtLintParams(indentSize=4, continuationIndentSize=4, experimentalRules=false, disabledRules=[], editorConfigPath=null)
```
I had to change the script slightly to use with the Kotlin DSL:
```
tasks.named<org.jmailen.gradle.kotlinter.tasks.LintTask>("lintKotlinMain") { // task name that fails
    println("--sourceSets--")
    sourceSets.all {
        println("${name} -> ${java.srcDirs}")
        println("${name} -> ${kotlin.sourceSets}")
    }
    println("--rules--")
    println(kotlinter.disabledRules.joinToString(","))
    println("--ktlint--")
    println(ktLintParams)
}
```

**Comment by henrik242** [comment]
If I put the `println` lines inside a `doLast { }`, the last line changes to `KtLintParams(indentSize=4, continuationIndentSize=4, experimentalRules=false, disabledRules=[no-wildcard-imports, import-ordering], editorConfigPath=null)` on 2.2.0.

On 2.3.0 it just fails, obviously.

**Comment by mateuszkwiecinski** [comment]
Thanks for all the valuable information 🙏 
The `ktLintParams` should be already filled in, in the configuration phase, so the `disabledRules=[]` shouldn't ever happen with your config.
Thanks again, and I'll try to narrow down possible scenarios why that could be happening 🤔

**Comment by mateuszkwiecinski** [comment]
Just FYI: I was able to identify the root cause of this issue. Your project configures all tasks in your project eagerly so kotlinter tasks aren't lazily configured and they access the extenion earlier than plugin expects. Previos plugin version worked because it used less efficient `project.afterEvaluate` which delayed tasks configuration.

As a solution I'll try to migrate the plugin to use Gradle Property API which should solve the issue. (cc: @jeremymailen (just in case if that doesn't make sense for you))

@henrik242 I would suggest you to investigate your project configuration as most probably eager tasks configuration slows down your build (you can confirm that by adding `tasks.register("shouldNotBeConfigured") { throw new GradleException() }` to your `build.gradle` and the build should still pass 👀

**Comment by jeremymailen** [comment]
Thank you for being so on top of this @mateuszkwiecinski! Sorry I was awol, it's been an exceedingly busy couple of weeks.

When you say the tasks were configured eagerly in this project, I guess I'm not spotting the code that indicates that -- can you point it out?

Do you mean: use Gradle `Property` or `Provider` objects as inputs for the format and lint tasks? If so, that sounds like the right solution. Thank you again for your work on this.

**Comment by lwasyl** [comment]
> When you say the tasks were configured eagerly in this project, I guess I'm not spotting the code that indicates that -- can you point it out?

There's nothing in the snippet posted, but since OP indicates it's a pretty complex multiproject build, it's not uncommon to have a plugin or other piece of common script do something like `project.tasks.all { }` or `tasks.whenTaskAdded { }`, which makes all registered tasks be realized as soon as they're registered. [Even Kotlin plugin had a bug that caused this](https://youtrack.jetbrains.com/issue/KT-31666).
In any case it seems like the only possible scenario of this bug happening, as in fact task getting created immediately would make it unaware of configuration provided in extension
