### ISSUE TITLE
How to disable rule for one package

### ISSUE THREAD

**Issue by VovaStelmashchuk** [jeremymailen/kotlinter-gradle#136]
I need to disable one rule for one package. Can implement this?

**Comment by jeremymailen** [comment]
Hi there. The most straightforward way is to suppress the rule in each source file:
https://ktlint.github.io/#faq-error-suppression

kotlinter includes ktlint's `.editorconfig` support, but I don't think it understands sophisticated file patterns, only `[*{kt,kts}]`. So that probably wouldn't work.

Finally, you can customize each link task:
https://github.com/jeremymailen/kotlinter-gradle#customizing-tasks
```groovy
lintKotlinMain {
  disabledRules = ["rule-1", "rule-1"]
}
```
But tasks are per-sourceSet, so unless your package of interest is in its own sourceSet, it will affect more files than you want.

Of course you can exclude your package from the sourceSet task it's in, then define a custom lint task to just cover that package with reduced rules, but this starts to feel laborious. It will work though.

**Comment by VovaStelmashchuk** [comment]
I created a [ticket in ktlint repo](https://github.com/pinterest/ktlint/issues/742). Guys from ktlint say it will be fix in next release (0.37).
