### ISSUE TITLE
KotlinPlugin should not enforce .editorconfig of the rootProject to be passed to Ktlint

### ISSUE THREAD

**Issue by dwursteisen** [jeremymailen/kotlinter-gradle#151]
**Current:** Creating a `.editorconfig` at the root of the project with a section name matching a directory name will never match.

Example of project structure: 

```
.editorconfig
build.gradle.kts
src/main/FileWithLintError.kt
src/test/NonToBeChecked.kt
```

Example of `.editorconfig`:
```
root = true

[**/main/**.{kt,kts}]
max_line_length=5
```

Ktlint will not apply the parameter from the `.editorconfig`. The purpose here is to have a specific parameter for main sources and another one for test sources.

**Expected:**:  Creating a `.editorconfig` at the root of the project with a section name matching a directory name will match and apply the parameter from the section.

The issue is that the the `.editorconfig` from the rootProject will be passed as editorconfig path if one exist
- https://github.com/jeremymailen/kotlinter-gradle/blob/master/src/main/kotlin/org/jmailen/gradle/kotlinter/KotlinterPlugin.kt#L163
- https://github.com/jeremymailen/kotlinter-gradle/blob/master/src/main/kotlin/org/jmailen/gradle/kotlinter/KotlinterPlugin.kt#L62

fast forward, this parameter is passed to ktlint in the LintWorkerRunnable : 
- https://github.com/jeremymailen/kotlinter-gradle/blob/master/src/main/kotlin/org/jmailen/gradle/kotlinter/tasks/lint/LintWorkerRunnable.kt#L71

fast forward, the editor path will be used as `alternativeEditorConfig` in ktlint
- https://github.com/pinterest/ktlint/blob/master/ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoader.kt#L59

The file path (the file that is being check) will be change, as `alternativeEditorConfig` is not null: 
instead of being `src/main/FileWithLintError.kt` it will be `<fullpath of .editorconfig>/FileWithLintError.kt`.
This new path is used only for section matching, and in this case will not match again the section from our .editorconfigfile.
as `<fullpath of .editorconfig>/FileWithLintError.kt`. will not match against `[**/main/**.{kt,kts}]`

You can confirm this behaviour (path change of the file analysed) using the test of ktlint: https://github.com/pinterest/ktlint/blob/master/ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoaderTest.kt#L267

**Proposed workaround:** Creating a .editorconfig in all directories excepting in the root directory. It will work only with project with with submodules.

**Proposed fixed:** 
The editorconfig path should [not be enforced by default but being a parameter of the plugin extension](https://github.com/jeremymailen/kotlinter-gradle/blob/master/src/main/kotlin/org/jmailen/gradle/kotlinter/KotlinterPlugin.kt#L62,75) with null value by default (ktlint should find the root editorconfig file anyway).

**Comment by jeremymailen** [comment]
Thank you for the detailed write up and it's a good catch.

Your suggestion should work and really the best course of action may be to completely remove the editorconfig parameter from kotlinter since the ktlint engine will automatically resolve editorconfig files up the tree from what I see here.

Honestly I find the ktlint highly misleading here and wonder if https://github.com/pinterest/ktlint/blob/master/ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoaderTest.kt#L267 is actually a bug. Do you know why they relocate the file path? I gather the ec4j engine will automatically apply paths from editor configs correctly in relation to the file. After all, the call one level up in ktlint already has the normalized path of the file.

I had wrongly assumed I needed to pass in the path of the editorconfig file if it was anywhere other than the current working directory (which would be the case in a multimodule project where the task is being run in a subdirectory).

**Comment by dwursteisen** [comment]
Hi !

> Your suggestion should work and really the best course of action may be to completely remove the editorconfig parameter from kotlinter since the ktlint engine will automatically resolve editorconfig files up the tree from what I see here.

My first intention would have be to let the user configure it, if needed. But for sake of simplicity, maybe you're right: getting ride of that and just let user put the file in the right folder (which will be 99% of the time in the root project I think)

> Honestly I find ktlint's api highly misleading here 

I think the same. The parameter name doesn't denote that the behaviour will change regarding if you're passing the parameter or not. 

> and wonder if https://github.com/pinterest/ktlint/blob/master/ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoaderTest.kt#L267 is actually a bug. Do you know why they relocate the file path? I gather the ec4j engine will automatically apply paths from editor configs correctly in relation to the file. After all, the call one level up in ktlint already has the normalized path of the file.

I went deeper : EC4J will look for the editor config that is in the path of the file that is checked. 
There is no way, according to my actual knowledge, at the moment, to tell EC4J to generate the configuration from a file and an editor config file from another path. So I think that the team behind ktlint bend the system a bit: keep the path of the alternative editor config file and append the file being check in that path.

After some through, I think that ktlint might not have introduced this alternative editor config path with EC4J unable to support loading alternative editor config file.

**Comment by jeremymailen** [comment]
I'll bundle this change with an upgrade to Kotlin 1.4 🤞

**Comment by dwursteisen** [comment]
👋 May I asked you what's your idea behind updating to Kotlin 1.4?

As Gradle depends on Kotlin 1.3.xx (depends of your gradle version), the last version of ktlint might depends of Kotlin 1.3.xx, are you not afraid to get compatibility issues between 1.3 and 1.4 ? Are you not afraid to go in a complicated situation?

Thanks!

**Comment by jeremymailen** [comment]
See https://github.com/jeremymailen/kotlinter-gradle/issues/144#issuecomment-679168845
I'd expect the update early this week.

I've already worked through potential compatibility issues, the only constraint will be that the next release of kotlinter will be 3.0.0 and will require kotlin 1.4+ and ktlint 0.38.1+.

If this causes issues for you, I can do a 2.5.0 release with just the fix for this issue, but I feel like it will be a short lived release.

**Comment by jeremymailen** [comment]
Separately, I wonder about JetBrains' decision to make `kotlinOptions.kotlinOptions` default to `1.4` in the `1.4.0` kotlin gradle plugins. I think what will happen is a lot of library authors will take this upgrade not realizing that the default artifact it produces won't be compatible with any of their consumers still using kotlin 1.3.

**Comment by jeremymailen** [comment]
https://github.com/jeremymailen/kotlinter-gradle/releases/tag/3.0.0
