### ISSUE TITLE
JCenter/Bintray are going down next month. Looks like this module is hosted there. Find a new home?

### ISSUE THREAD

**Issue by gefilte** [jeremymailen/kotlinter-gradle#173]
https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/

So by end of April this hosting will be unavailable. Have a new home in mind?

**Comment by jeremymailen** [comment]
Thanks for the heads up!

We don't publish to to jcenter (gradle plugins portal is where the artifacts get pushed).

It looks like we can switch over to pulling all dependencies from `mavenCentral()` with the noteworth exception of trove4j https://youtrack.jetbrains.com/issue/KT-44730. Assume that will get resolved in time.

I'll make the switch in a `3.4.0` release. We've got a bit of time since it looks like jcenter will continue to serve packages until Feb 1, 2022.

**Comment by jeremymailen** [comment]
3.4.0 didn't fully get rid of jcenter. It's still providing trove4j... just waiting on the owners to resolve, but we've got time.

**Comment by jeremymailen** [comment]
Fixed in #184
