### ISSUE TITLE
Multi modules project not working with java folder

### ISSUE THREAD

**Issue by tsuharesu** [jeremymailen/kotlinter-gradle#25]
I have a Android app and a plain kotlin module. Since kotlin accepts files inside a `src/main/java` folder, I have files in this folder. However, when running `./gradlew ktlin`, it returns `NO SOURCE`.

I just tried using `ktlint` directly (https://github.com/shyiko/ktlint#-with-gradle) and it worked.

**Comment by jeremymailen** [comment]
Sorry about the delay. I'll try to look this weekend.

Is this a module within a multi-module build for an android app? If the module with kotlin source is an "android library" module, it should pick kotlin files under `src/main/java`: https://github.com/jeremymailen/kotlinter-gradle/blob/master/src/main/kotlin/org/jmailen/gradle/kotlinter/KotlinterPlugin.kt#L59

If it's just a module using `kotlin-jvm` it might only find the conventional kotlin sourceSets under `src/main/kotlin` since I'm using the plugin's interface to tell me.

If you bump gradle log level up to debug that output might help me troubleshoot.

**Comment by tsuharesu** [comment]
Hey man, no worries. As I said, I am using ktlint and it is working. 

It is a project with some modules (inspired by clean architecture). The main one is UI with Android plugin, other are simple kotlin modules with only `apply plugin: 'kotlin'`, not `kotlin-jvm` (I didn't even know there was this plugin).

**Comment by jeremymailen** [comment]
I created a single module project with kotlin source under both src/main/kotlin and src/main/java and the kotlin compiler and kotlinter see both.

Can you give a little more info about your project structure to help troubleshoot and the output of:
`gradle -d lintKotlin | grep lintKotlin`

For reference by build file is like:
```groovy
buildscript {
    ext.kotlin_version = '1.1.60'
    repositories {
        jcenter()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'org.jmailen.gradle:kotlinter-gradle:1.5.1'
    }
}
plugins {
    id 'java'
    id 'application'
    id 'idea'
}
apply plugin: 'kotlin'
apply plugin: 'org.jmailen.kotlinter'
...
```
And I get output like:
```
...
14:56:35.745 [DEBUG] [org.gradle.api.Task] lintKotlinMain linting: src/main/kotlin/jmailen/slakoverflow/stackoverflow/Client.kt
14:56:35.752 [DEBUG] [org.gradle.api.Task] lintKotlinMain linting: src/main/kotlin/jmailen/slakoverflow/slack/CommandResponse.kt
14:56:35.754 [DEBUG] [org.gradle.api.Task] lintKotlinMain linting: src/main/java/org/jmailen/ThingKotlin.kt
14:56:35.755 [DEBUG] [org.gradle.api.Task] lintKotlinMain linting: src/main/java/org/jmailen/Thing.java
14:56:35.755 [DEBUG] [org.gradle.api.Task] lintKotlinMain ignoring non Kotlin file: src/main/java/org/jmailen/Thing.java
...
```

**Comment by tsuharesu** [comment]
Hmm, tried again with version 1.6.0 and it seems to work. Thanks!
