### ISSUE TITLE
Regression:  3.11.1 doesn't seem to read `disabled_rules` from .editorconfig anymore

### ISSUE THREAD

**Issue by henrik242** [jeremymailen/kotlinter-gradle#262]
After upgrading from 3.10.0 I had to specify `disabledRules` in the gradle `kotlinter { }` block instead of relying on `disabled_rules` in .editorconfig.

**Comment by mateuszkwiecinski** [comment]
Hey @henrik242 👋 Thanks for reporting the issue. There were indeed some changes around `editorConfig` properties, but I don't see an obvious mistake in the updated implementation 👀 Plus, I was able to set the `disabled_rules` in my [personal project](https://github.com/usefulness/diffuse/blob/master/.editorconfig#L14). 

I recall Ktlint had its own config-caching mechanism, which I suspect as the root cause of this issue. Can you try running `./gradlew --stop` before running any of kotlinter's tasks? 
(so, just to be clear: I'm asking you to revert to old config, with `disabled_rules` set in `.editorconfig` only, and then run `./gradlew  --stop` and then `./gradlew lintKotlin`)
