### ISSUE TITLE
For version 3.13 can't resolve sources from IDE

### ISSUE THREAD

**Issue by StylianosGakis** [jeremymailen/kotlinter-gradle#314]
Basically when trying to click on "Download sources" from the IDE I get the error:

```
> Could not resolve all files for configuration ':build-logic:convention:downloadSources_b42c9a83-677a-429b-97bb-bb8d27ed7644'.
   > Could not find kotlinter-gradle-3.13.0-sources.jar (org.jmailen.gradle:kotlinter-gradle:3.13.0).
```

Is this some temporary error, something wrong in the build pipeline, or something else on my end potentially? Do you have some idea maybe?

**Comment by mateuszkwiecinski** [comment]
I confirm they seem to be missing: https://plugins.gradle.org/m2/org/jmailen/gradle/kotlinter-gradle/3.13.0/  And they seem to be missing since 3.4.1 ([3.4.0](https://plugins.gradle.org/m2/org/jmailen/gradle/kotlinter-gradle/3.4.0/) is the latest release that has `-sources` artifact published)👀 
I recall I did some clean-ups around, but my local builds were producing valid artifacts: https://github.com/jeremymailen/kotlinter-gradle/pull/306#discussion_r1064024806 interesting 👀

**Comment by StylianosGakis** [comment]
Aha so it is publishing them locally but not when doing it in CI then? Do you have an idea of why that is, is it from the bump of `com.gradle.plugin-publish`, does it need some special configuration?
