### ISSUE TITLE
Lint task sometimes does not re-run when editorconfig changes

### ISSUE THREAD

**Issue by jeremymailen** [jeremymailen/kotlinter-gradle#327]
Although we are supposed to consider the editorconfig file contents a build input and re-run lint tasks when it changes, somehow this isn't happening sometimes. It often leads users to perceive that one of their editorconfig settings is not working.
Reference #324 and #321

**Comment by christophsturm** [comment]
This problem happens to me all of the time. I don't know where the editorconfig file is cached but `git clean -fxd` fixes it for me.

**Comment by bravik** [comment]
`./gradlew --stop && ./gradlew :link:formatKotlin`

**Comment by jeremymailen** [comment]
Yeah, this is clearly a bug, but I need to find time to track it down and fix it. PRs welcome if someone else sees the solution.

**Comment by mateuszkwiecinski** [comment]
I'm unable to create a PR, but I can link the root cause: https://github.com/jeremymailen/kotlinter-gradle/blob/2023cbb75fc4d0287317cb25a295a68b6accab71/src/main/kotlin/org/jmailen/gradle/kotlinter/tasks/ConfigurableKtLintTask.kt#L31-L35 - the `if` should be dropped. The exact failing scenario (with a bit of explanation) can be found on [kotlinlang slack](https://kotlinlang.slack.com/archives/CKS3XG0LS/p1679433820380369?thread_ts=1679432805.524049&cid=CKS3XG0LS)

**Comment by jeremymailen** [comment]
Thanks @mateuszkwiecinski I can definitely make a PR when I get back home from the holidays.
You should still have permission to make PRs, merge, release etc since you're still a contributor but if you're running into trouble I can try to fix whatever's gone wrong.
