### ISSUE TITLE
Upgrade to ktlint 0.49.1

### ISSUE THREAD

**Issue by jasonab** [jeremymailen/kotlinter-gradle#331]
My team is eager to try out the new formatting rules, but I know there were a ton of breaking API changes in this version. Do you have this already in hand, or do you need some outside contributions?

**Comment by jeremymailen** [comment]
The PR is ready to go and working #330. Was just waiting a day or so to see if there were an review comments.

For this plugin, not too bad. The main people who will be impacted by 0.49.x will be those who develop custom Rules and Reporters. Also there might be new lint errors on some projects due to rules moved out of experimental.

Thanks!

**Comment by jasonab** [comment]
great, thanks for all of your efforts as always
