### ISSUE TITLE
FormatKotlin task doesn't support pass path of the files to format by argument

### ISSUE THREAD

**Issue by ljfantin** [jeremymailen/kotlinter-gradle#85]
Hi
I want to use the formatKotlin task from command line and pass by parameter the file names to format.
I don't know if it is not possible or there are an issue.
Please help me
Thanks

**Comment by ljfantin** [comment]
Ktlint supports installing git pre-commit hook, that will check style violations on git commit. Would be nice to add this as a Gradle task to simplify setup for the project.

**Comment by jeremymailen** [comment]
Are you wanting kotlinter-gradle to perform the work triggered by a pre-commit hook or to install a pre-commit hook (or both)?

**Comment by jeremymailen** [comment]
For installing a pre-commit hook, we don't necessarily want to assume the presence of git (even though it's quite common) and a given organization may have pre-commit hooks already which do multiple things. It seems like a good candidate for organizations to automate individually rather than the plugin decide for them.

The hook might be as simple as `./gradlew lintKotlin` since the plugin efficiently implements incremental build only checking source sets which have changed.

For a more efficient implementation which only checks the files in the commit, a [custom task](https://github.com/jeremymailen/kotlinter-gradle#custom-tasks) could be defined taking the commit files as inputs to `source`.

**Comment by jeremymailen** [comment]
Closing for now unless there more that can be done to help.
